### ISSUE TITLE
Example fails to run

### ISSUE THREAD

**Issue by frankcash** [fraserxu/react-dropdown#23]
I followed the provided instructions `$ cd example && npm install && npm run watch` but I receive the following error:

### npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/4.1.2/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'browser-sync' ]
2 info using npm@2.14.6
3 info using node@v4.1.2
4 verbose run-script [ 'prebrowser-sync', 'browser-sync', 'postbrowser-sync' ]
5 info prebrowser-sync react-chartist@
6 info browser-sync react-chartist@
7 verbose unsafe-perm in lifecycle true
8 info react-chartist@ Failed to exec browser-sync script
9 verbose stack Error: react-chartist@ browser-sync: `browser-sync start --server --files './bundle.js'`
9 verbose stack spawn ENOENT
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:17:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid react-chartist@
11 verbose cwd /Users/frankcash/Code/react-dropdown/example
12 error Darwin 14.1.0
13 error argv "/usr/local/Cellar/node/4.1.2/bin/node" "/usr/local/bin/npm" "run" "browser-sync"
14 error node v4.1.2
15 error npm  v2.14.6
16 error file sh
17 error code ELIFECYCLE
18 error errno ENOENT
19 error syscall spawn
20 error react-chartist@ browser-sync: `browser-sync start --server --files './bundle.js'`
20 error spawn ENOENT
21 error Failed at the react-chartist@ browser-sync script 'browser-sync start --server --files './bundle.js''.
21 error This is most likely a problem with the react-chartist package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     browser-sync start --server --files './bundle.js'
21 error You can get their info via:
21 error     npm owner ls react-chartist
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]

```

### console output
```
Error: Cannot find module 'react' from '/Users/frankcash/Code/react-dropdown/example'
Error: Cannot find module 'react' from '/Users/frankcash/Code/react-dropdown/dist'
[Error: write after end]
Error: Cannot find module 'react-dom' from '/Users/frankcash/Code/react-dropdown/dist'
[Error: write after end]
Error: Cannot find module 'classnames' from '/Users/frankcash/Code/react-dropdown/dist'
[Error: write after end]
```

**Comment by frankcash** [comment]
I would say the needed modules aren't being provided in the `package.json`

**Comment by fraserxu** [comment]
@frankcash Thanks for reporting. Sorry that I haven't updated the example for a while. Will have a look now.

**Comment by fraserxu** [comment]
@frankcash Fixed. The example should work now.
